package com.model;

/**
 * TTimu generated by MyEclipse Persistence Tools
 */

public class TTimu implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String name;

	private String xuanxianga;

	private String xuanxiangb;

	private String xuanxiangc;

	private String xuanxiangd;

	private String daan;

	private Integer fenshu;

	private String del;

	private String fenlei;

	public String getFenlei() {
		return fenlei;
	}

	public void setFenlei(String fenlei) {
		this.fenlei = fenlei;
	}

	// Constructors

	/** default constructor */
	public TTimu()
	{
	}

	/** full constructor */
	public TTimu(String name, String xuanxianga, String xuanxiangb,
			String xuanxiangc, String xuanxiangd, String daan, Integer fenshu,
			String del)
	{
		this.name = name;
		this.xuanxianga = xuanxianga;
		this.xuanxiangb = xuanxiangb;
		this.xuanxiangc = xuanxiangc;
		this.xuanxiangd = xuanxiangd;
		this.daan = daan;
		this.fenshu = fenshu;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getXuanxianga()
	{
		return this.xuanxianga;
	}

	public void setXuanxianga(String xuanxianga)
	{
		this.xuanxianga = xuanxianga;
	}

	public String getXuanxiangb()
	{
		return this.xuanxiangb;
	}

	public void setXuanxiangb(String xuanxiangb)
	{
		this.xuanxiangb = xuanxiangb;
	}

	public String getXuanxiangc()
	{
		return this.xuanxiangc;
	}

	public void setXuanxiangc(String xuanxiangc)
	{
		this.xuanxiangc = xuanxiangc;
	}

	public String getXuanxiangd()
	{
		return this.xuanxiangd;
	}

	public void setXuanxiangd(String xuanxiangd)
	{
		this.xuanxiangd = xuanxiangd;
	}

	public String getDaan()
	{
		return this.daan;
	}

	public void setDaan(String daan)
	{
		this.daan = daan;
	}

	public Integer getFenshu()
	{
		return this.fenshu;
	}

	public void setFenshu(Integer fenshu)
	{
		this.fenshu = fenshu;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}